baseURL = "https://blog.skycoin.net/"
languageCode = "en-us"
title = "Skycoin Blog"

#googleAnalytics = ""
#disqusShortname = ""

# hugo-xmin specific variables
theme = "skycoin"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 3

[[menu.footer]]
  name = "skycoin.net"
  url = "https://www.skycoin.net/"
  weight = 1

[[menu.footer]]
  name = "Github"
  url = "https://github.com/skycoin"
  weight = 2

[[menu.footer]]
  name = "Twitter"
  url = "https://twitter.com/skycoinproject"
  weight = 3

[[menu.footer]]
  name = "Reddit"
  url = "https://reddit.com/r/SkycoinProject"
  weight = 4

[[menu.footer]]
  name = "Telegram"
  url = "https://t.me/Skycoin"
  weight = 5

[[menu.footer]]
  name = "Blockchain Explorer"
  url = "https://explorer.skycoin.net/"
  weight = 6

[author]
  name = "Skycoin"

[params]
  keywords = "skycoin"
  rss = "/index.xml"
  telegram = "https://t.me/Skycoin"
  description = "Skycoin Project Updates"
  email = ""
  github = "skycoin"
  #gitlab = "gitlab id"
  twitter = "skycoinproject"
  #linkedin = "linkedin id"

[Languages]
  [Languages.en]
  weight = 0
  [Languages.ru]
  weight = 1
  title = "Skycoin Блог"
