baseURL = "https://blog.skycoin.net/"
languageCode = "en-us"
title = "Skycoin Blog"
defaultContentLanguage = "en"

googleAnalytics = "UA-105234182-1"
#disqusShortname = ""

# hugo-xmin specific variables
theme = "skycoin"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "murphy"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    identifier = "categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 3

[[menu.footer]]
  name = "skycoin.net"
  url = "https://www.skycoin.net/"
  weight = 1

[[menu.footer]]
  name = "Github"
  url = "https://github.com/skycoin"
  weight = 2

[[menu.footer]]
  name = "Twitter"
  url = "https://twitter.com/skycoinproject"
  weight = 3

[[menu.footer]]
  name = "Reddit"
  url = "https://reddit.com/r/SkycoinProject"
  weight = 4

[[menu.footer]]
  name = "Telegram"
  url = "https://t.me/Skycoin"
  weight = 5

[[menu.footer]]
  name = "Blockchain Explorer"
  url = "https://explorer.skycoin.net/"
  weight = 6

[author]
  name = "Skycoin"

[params]
  keywords = "skycoin"
  rss = "/index.xml"
  telegram = "https://t.me/Skycoin"
  description = "Skycoin Project Updates"
  email = ""
  github = "skycoin"
  twitter = "skycoinproject"
  twitterAnalytics = "ny03t"

[Languages]
[Languages.en]
  weight = -1
  title = "Skycoin Blog"
  languageName = "English"

[Languages.zh]
  weight = 1
  title = "天空币博客"
  hasCJKLanguage = true
  languageName = "中文"

[Languages.ru]
  weight = 2
  title = "Skycoin Блог"
  languageName = "Русский"

[Languages.kr]
  weight = 3
  title = "Skycoin 블로그"
  languageName = "한국어"

[Languages.es]
    weight = 4
    title = "Skycoin Blog"
    languageName = "Español"

[Languages.de]
    weight = 5
    title = "Skycoin Blog"
    languageName = "Deutsch"

[Languages.jp]
    weight = 6
    title = "Skycoin Blog"
    languageName = "日本語"

[Languages.gr]
    weight = 7
    title = "Skycoin Blog"
    languageName = "Ελληνικά"

[Languages.fr]
    weight = 8
    title = "Skycoin Blog"
    languageName = "Français"

[Languages.nl]
    weight = 9
    title = "Skycoin Blog"
    languageName = "Nederlands"

[[menu.languages]]
  name = "English"
  weight = -1
  url = "/"
[[menu.languages]]
  name = "中文"
  weight = 1
  url = "/zh/"
[[menu.languages]]
  name = "Русский"
  weight = 2
  url = "/ru/"
[[menu.languages]]
  name = "한국어"
  weight = 3
  url = "/kr/"
[[menu.languages]]
  name = "Español"
  weight = 4
  url = "/es/"
[[menu.languages]]
  name = "Deutsch"
  weight = 5
  url = "/de/"
[[menu.languages]]
  name = "日本語"
  weight = 6
  url = "/jp/"
[[menu.languages]]
  name = "Ελληνικά"
  weight = 7
  url = "/gr/"
[[menu.languages]]
  name = "Français"
  weight = 8
  url = "/fr/"
[[menu.languages]]
  name = "Nederlands"
  weight = 9
  url = "/nl/"
